#!/command/with-contenv /bin/ash
# shellcheck shell=bash

log_prefix="[init-db-wait]"

wait_for_postgres() {
	local attempt_num=1
	local -r max_attempts=5

	echo "${log_prefix} Waiting for PostgreSQL to start..."

	local -r host="${DB_HOST}"
	local -r port="${DB_PORT:-5432}"
	local -r user="${DB_USER:-memoria}"

	# Disable warning, host and port can't have spaces
	# shellcheck disable=SC2086
	while [ ! "$(pg_isready -h ${host} -p ${port} --username ${user})" ]; do

		if [ $attempt_num -eq $max_attempts ]; then
			echo "${log_prefix} Unable to connect to database."
			exit 1
		else
			echo "${log_prefix} Attempt $attempt_num failed! Trying again in 5 seconds..."
		fi

		attempt_num=$(("$attempt_num" + 1))
		sleep 5
	done
	# Extra in case this is a first start
	sleep 5
	echo "Connected to PostgreSQL"
}

if [[ "${DATABASE_TYPE}" == "postgres" ]]; then
	echo "${log_prefix} Waiting for PostgreSQL to report ready"
	wait_for_postgres
fi

echo "${log_prefix} Database is ready"
