#!/command/with-contenv /bin/ash
# shellcheck shell=bash

log_prefix="[init-db-wait]"

wait_for_postgres() {
    attempt_num=1
    max_attempts=5

    echo "${log_prefix} Waiting for PostgreSQL to start..."

    host="${MEMORIA_DB_HOST}"
    user="${MEMORIA_DB_USER}"
    port="${DB_PORT}"

    if [ -z "${port}" ]; then
        port="5432"
    fi
    if [ -z "${user}" ]; then
        user="memoria"
    fi
    if [ -z "${host}" ]; then
        host="memoria"
    fi

    # Use a while loop checking the exit status of pg_isready (0 on success)
    while ! pg_isready -h "${host}" -p "${port}" --username "${user}"; do

        if [ "$attempt_num" -ge "$max_attempts" ]; then # Use -ge for greater than or equal
            echo "${log_prefix} Unable to connect to database after $attempt_num attempts."
            exit 1
        fi

        echo "${log_prefix} Attempt $attempt_num failed! Trying again in 5 seconds..."

        # Correct Ash arithmetic syntax
        attempt_num=$((attempt_num + 1))
        sleep 5
    done

    # Extra sleep in case this is a first start
    sleep 5
    echo "${log_prefix} Connected to PostgreSQL"
}

if [ "${MEMORIA_DATABASE_TYPE}" = "postgresql" ]; then
    echo "${log_prefix} Waiting for PostgreSQL to report ready"
    wait_for_postgres
fi

echo "${log_prefix} Database is ready"
