# https://taskfile.dev
version: "3"
# Variables that can be used across sub-Taskfiles (if passed down or read by them)
vars:
  PROJECT_NAME: memoria
  PYTHON_VERSION: 3.12
  DOCKER_IMAGE_NAME: "{{.PROJECT_NAME}}:{{.VERSION}}" # Dynamic image name
includes:
  backend: ./src-backend
  src-frontend: ./src-frontend
  docs: ./src-docs
tasks:
  default:
    cmds:
      - task --list-all
    silent: true
    desc: List all available tasks
  # -----------------------------------------------------------
  # Version Management
  # -----------------------------------------------------------
  version:sync:
    desc: Synchronizes the version to pyproject.toml and package.json files
    cmds:
      - python scripts/sync_version.py {{.CLI_ARGS}}
    sources:
      - VERSION
      - scripts/sync_version.py
      - src-backend/pyproject.toml
      - src-docs/pyproject.toml
      - src-frontend/package.json
  # -----------------------------------------------------------
  # Global Dependency Management
  # -----------------------------------------------------------
  deps:install:
    desc: Install all Python (uv workspace) and Node.js (pnpm) dependencies.
    cmds:
      - task: backend:deps:install
      - task: docs:deps:install
      - task: src-frontend:deps:install
      - echo "All dependencies installed."
  # -----------------------------------------------------------
  # Development Commands
  # -----------------------------------------------------------
  dev:
    desc: Starts all development servers (backend, src-frontend, docs).
    cmds:
      - echo "Starting dev servers..."
      - task: backend:dev &
      - task: src-frontend:dev &
      - task: docs:dev &
      - wait # Wait for all background tasks to complete (or use Ctrl+C to stop)
  # -----------------------------------------------------------
  # Build Commands
  # -----------------------------------------------------------
  build:
    desc: Builds all project artifacts (backend, src-frontend, docs).
    cmds:
      - task: version:sync # Ensure versions are synced before building
      - task: backend:build
      - task: src-frontend:build
      - task: docs:build
      - echo "All projects built."
  # -----------------------------------------------------------
  # Testing & Linting
  # -----------------------------------------------------------
  test:
    desc: Runs all tests across the backend.
    cmds:
      - task: backend:test
  lint:
    desc: Runs all linting checks across the backend and src-frontend.
    cmds:
      - task: backend:lint
      - task: src-frontend:lint
  # -----------------------------------------------------------
  # Cleanup
  # -----------------------------------------------------------
  clean:
    desc: Cleans build artifacts and caches from all projects.
    cmds:
      - task: backend:clean
      - task: src-frontend:clean
      - task: docs:clean
      - echo "All projects cleaned."
  # -----------------------------------------------------------
  # API Client Generation Workflow
  # -----------------------------------------------------------
  api:update-client:
    desc: Exports backend OpenAPI schema and generates src-frontend API client.
    cmds:
      - task: backend:api:export-schema
      - task: src-frontend:api:generate-client
  repomix:
    cmds:
      - repomix --style markdown --remove-comments --ignore src-frontend/.prettierignore,src-frontend/.stylelintignore,src-frontend/eslint.config.js,src-frontend/index.html,src-frontend/openapi-ts.config.ts,src-frontend/pnpm-workspace.yaml,src-frontend/README.md,src-frontend/vite.config.ts,src-frontend/tsconfig.app.json,src-frontend/tsconfig.json,src-frontend/tsconfig.node.json,src-frontend/public/,docker/,src-frontend/.env,src-frontend/.gitignore,src-backend/memoria/migrations/,api-spec.json,docs/ --remove-empty-lines .
