# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  reset:
    cmds:
      - rm db.sqlite3 || true
      - rm -r ./logs/ || true
      - rm -r ./media/ || true
      - uv run manage.py migrate
  indexholmes:
    cmds:
      - uv run manage.py index --hash-threads 16 --view-group "Holmes Viewers" --edit-group "Holmes Editors" --root-dir "D:\Pictures\Scans" "D:\Pictures\Scans\Parents'"
  indexclaudia:
    cmds:
      - uv run manage.py index --hash-threads 16 --view-group "Claudia Viewers" --edit-group "Claudia Editors" --root-dir "D:\Pictures\Scans" "D:\Pictures\Scans\Grandma's"
  indexanderson:
    cmds:
      - uv run manage.py index --hash-threads 16 --view-group "Anderson Viewers" --edit-group "Anderson Editors" --root-dir "D:\Pictures\Scans" "D:\Pictures\Scans\Anderson Family"
  indexsubset:
    cmds:
      - uv run manage.py index --hash-threads 16 --view-group "Anderson Viewers" --edit-group "Anderson Editors" --root-dir "D:\Pictures\Scans" "D:\Pictures\Scans\Anderson Family\Box 6\2002 - 08"
  makemigrations:
    cmds:
      - uv run manage.py makemigrations
  exportschema:
    deps:
      - exportopenapi
      - generateapiclient
  exportopenapi:
    env:
      MEMORIA_DEBUG: "true"
    cmds:
      - uv run manage.py export_openapi_schema --output schema.json --sorted --indent 2
  generateapiclient:
    dir: "frontend"
    cmds:
      - pnpm run generate-api-client
      - pnpm run format
