# https://taskfile.dev
version: "3"
tasks:
  default:
    cmds:
      - task --list-all
    silent: true
    desc: List backend-specific tasks
  deps:install:
    desc: Install backend Python dependencies using uv.
    dir: ./src-backend
    cmds:
      - uv sync --dev
  dev:
    desc: Runs the Django development server.
    dir: .
    cmds:
      - uv run python manage.py runserver
    deps: ["deps:install"]
  test:
    desc: Runs backend tests with pytest.
    dir: .
    cmds:
      - uv run pytest
    deps: ["deps:install"]
  lint:
    desc: Runs ruff, mypy checks.
    dir: .
    cmds:
      - uv run ruff check . --fix
      - uv run mypy .
    deps: ["deps:install"]
  migrations:makemigrations:
    desc: Creates Django migrations.
    dir: .
    cmds:
      - uv run python manage.py makemigrations
    deps: ["deps:install"]
  migrations:migrate:
    desc: Applies Django migrations.
    dir: .
    cmds:
      - uv run python manage.py migrate
    deps: ["deps:install"]
  clean:
    desc: Cleans backend build artifacts and caches.
    dir: .
    cmds:
      - rm -rf __pycache__ .mypy_cache .pytest_cache .coverage coverage_html_report
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete
    silent: true
  api:export-schema:
    desc: Exports the OpenAPI schema from the backend.
    dir: ./src-backend
    env:
      MEMORIA_DEBUG: "true"
    cmds:
      - uv run python manage.py export_openapi_schema --output ../api-spec.json --sorted --indent 2
    deps: ["deps:install"]
  reset:
    cmds:
      - rm data/db.sqlite3 || true
      - rm -r ./logs/ || true
      - rm -r ./media/ || true
      - uv run manage.py migrate
  indexholmes:
    cmds:
      - uv run manage.py index --hash-threads 16 --view-group "Holmes Viewers" --edit-group "Holmes Editors" --root-dir "D:\Pictures\Scans" "D:\Pictures\Scans\Parents'"
  indexclaudia:
    cmds:
      - uv run manage.py index --hash-threads 16 --view-group "Claudia Viewers" --edit-group "Claudia Editors" --root-dir "D:\Pictures\Scans" "D:\Pictures\Scans\Grandma's"
  indexanderson:
    cmds:
      - uv run manage.py index --hash-threads 16 --view-group "Anderson Viewers" --edit-group "Anderson Editors" --root-dir "D:\Pictures\Scans" "D:\Pictures\Scans\Anderson Family"
  indexsubset:
    cmds:
      - uv run manage.py index --hash-threads 16 --view-group "Anderson Viewers" --edit-group "Anderson Editors" --root-dir "D:\Pictures\Scans" "D:\Pictures\Scans\Anderson Family\Box 6\2002 - 08"
  repomix:
    cmds:
      - repomix --style markdown --remove-comments --include memoria/models,memoria/routes --ignore memoria/routes/.todo/ --remove-empty-lines .
