// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { AuthGetCsrfTokenData, AuthGetCsrfTokenResponse, AuthLoginData, AuthLoginResponse, AuthLogoutData, AuthLogoutResponse, FolderListRootsData, FolderListRootsResponse, FolderGetDetailsData, FolderGetDetailsResponse, ImageGetDateData, ImageGetDateResponse, ImageGetLocationData, ImageGetLocationResponse, ImageGetMetadataData, ImageGetMetadataResponse, ImageGetPeopleData, ImageGetPeopleResponse, ImageGetPetsData, ImageGetPetsResponse, ImageGetThumbInfoData, ImageGetThumbInfoResponse, UserCreateData, UserCreateResponse, UserGetInfoData, UserGetInfoResponse, UserEditInfoData, UserEditInfoResponse, UserGetProfileData, UserGetProfileResponse, UserEditProfileData, UserEditProfileResponse, UserGetGroupsData, UserGetGroupsResponse, UserSetGroupsData, UserSetGroupsResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Csrf Token
 */
export const authGetCsrfToken = <ThrowOnError extends boolean = false>(options?: Options<AuthGetCsrfTokenData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AuthGetCsrfTokenResponse, unknown, ThrowOnError>({
        url: '/api/auth/csrf/',
        ...options
    });
};

/**
 * Login
 */
export const authLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthLoginResponse, unknown, ThrowOnError>({
        url: '/api/auth/login/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Logout
 */
export const authLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthLogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AuthLogoutResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/auth/logout/',
        ...options
    });
};

/**
 * List Image Folders
 * List root image folders with permission filtering
 */
export const folderListRoots = <ThrowOnError extends boolean = false>(options?: Options<FolderListRootsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<FolderListRootsResponse, unknown, ThrowOnError>({
        url: '/api/folder/',
        ...options
    });
};

/**
 * Get Image Folder
 * Get details of a specific image folder with children and images
 */
export const folderGetDetails = <ThrowOnError extends boolean = false>(options: Options<FolderGetDetailsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<FolderGetDetailsResponse, unknown, ThrowOnError>({
        url: '/api/folder/{folder_id}/',
        ...options
    });
};

/**
 * Get Image Date
 */
export const imageGetDate = <ThrowOnError extends boolean = false>(options: Options<ImageGetDateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ImageGetDateResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/image/{image_id}/date/',
        ...options
    });
};

/**
 * Get Image Location
 */
export const imageGetLocation = <ThrowOnError extends boolean = false>(options: Options<ImageGetLocationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ImageGetLocationResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/image/{image_id}/location/',
        ...options
    });
};

/**
 * Get Image Details
 */
export const imageGetMetadata = <ThrowOnError extends boolean = false>(options: Options<ImageGetMetadataData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ImageGetMetadataResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/image/{image_id}/metadata/',
        ...options
    });
};

/**
 * Get Image People
 */
export const imageGetPeople = <ThrowOnError extends boolean = false>(options: Options<ImageGetPeopleData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ImageGetPeopleResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/image/{image_id}/people/',
        ...options
    });
};

/**
 * Get Image Pets
 */
export const imageGetPets = <ThrowOnError extends boolean = false>(options: Options<ImageGetPetsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ImageGetPetsResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/image/{image_id}/pets/',
        ...options
    });
};

/**
 * Get Image Thumbnail Info
 */
export const imageGetThumbInfo = <ThrowOnError extends boolean = false>(options: Options<ImageGetThumbInfoData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ImageGetThumbInfoResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/image/{image_id}/thumbnail/',
        ...options
    });
};

/**
 * Create User
 */
export const userCreate = <ThrowOnError extends boolean = false>(options: Options<UserCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UserCreateResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/user/create/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get User Info
 */
export const userGetInfo = <ThrowOnError extends boolean = false>(options?: Options<UserGetInfoData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UserGetInfoResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/user/me/',
        ...options
    });
};

/**
 * Edit User Info
 */
export const userEditInfo = <ThrowOnError extends boolean = false>(options: Options<UserEditInfoData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UserEditInfoResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/user/me/edit/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Profile
 */
export const userGetProfile = <ThrowOnError extends boolean = false>(options?: Options<UserGetProfileData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UserGetProfileResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/user/profile/',
        ...options
    });
};

/**
 * Edit Profile
 */
export const userEditProfile = <ThrowOnError extends boolean = false>(options: Options<UserEditProfileData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UserEditProfileResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/user/profile/edit/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get User Groups
 */
export const userGetGroups = <ThrowOnError extends boolean = false>(options: Options<UserGetGroupsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<UserGetGroupsResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/user/{user_id}/groups',
        ...options
    });
};

/**
 * Set User Groups
 */
export const userSetGroups = <ThrowOnError extends boolean = false>(options: Options<UserSetGroupsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UserSetGroupsResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/user/{user_id}/groups',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};
