#!/command/with-contenv /bin/ash
# shellcheck shell=bash
log_prefix="[init-migrations]"

echo "${log_prefix} Apply database migrations..."

cd /app/memoria/

# The whole migrate, with flock, needs to run as the right user
exec s6-setuidgid memoria \
    python3 manage.py migrate --skip-checks --no-input
