// This file is auto-generated by @hey-api/openapi-ts

export type AlbumAddImageInSchema = {
  /**
   * The id of the image to add to the album
   */
  image_ids?: Array<number>;
};

export type AlbumBasicReadOutSchema = {
  /**
   * Timestamp when the object was created
   */
  created_at: string;
  /**
   * The description of the album
   */
  description?: string | null;
  /**
   * Groups allowed to edit this object
   */
  edit_groups?: Array<GroupSchemaOut>;
  /**
   * The unique identifier of the object
   */
  id: number;
  /**
   * The count of images in this album
   */
  image_count: number;
  /**
   * The name of the album
   */
  name: string;
  /**
   * Timestamp when the object was last updated
   */
  updated_at: string;
  /**
   * Groups allowed to view this object
   */
  view_groups?: Array<GroupSchemaOut>;
};

export type AlbumCreateInSchema = {
  /**
   * The description of the album
   */
  description?: string | null;
  /**
   * IDs of Groups allowed to edit
   */
  edit_group_ids?: Array<number>;
  /**
   * The name of the album
   */
  name: string;
  /**
   * IDs of Groups allowed to view
   */
  view_group_ids?: Array<number>;
};

export type AlbumRemoveImageInSchema = {
  /**
   * The id of the image to remove from the album
   */
  image_ids?: Array<number>;
};

export type AlbumSortUpdateInSchema = {
  /**
   * The new order of the images, with the index being the new position in the album
   */
  sorting: Array<number>;
};

export type AlbumUpdateInSchema = {
  /**
   * The new description of the album
   */
  description?: string | null;
  /**
   * New list of Group IDs allowed to edit
   */
  edit_group_ids?: Array<number> | null;
  /**
   * The new name of the album
   */
  name?: string | null;
  /**
   * New list of Group IDs allowed to view
   */
  view_group_ids?: Array<number> | null;
};

export type AlbumWithImagesOutSchema = {
  /**
   * Timestamp when the object was created
   */
  created_at: string;
  /**
   * The description of the album
   */
  description?: string | null;
  /**
   * Groups allowed to edit this object
   */
  edit_groups?: Array<GroupSchemaOut>;
  /**
   * The unique identifier of the object
   */
  id: number;
  /**
   * The count of images in this album
   */
  image_count: number;
  /**
   * The ids of the images in this album in sorted order
   */
  image_ids: Array<number>;
  /**
   * The name of the album
   */
  name: string;
  /**
   * Timestamp when the object was last updated
   */
  updated_at: string;
  /**
   * Groups allowed to view this object
   */
  view_groups?: Array<GroupSchemaOut>;
};

export type AuthLoginSchemaReadable = {
  /**
   * The user's login name.
   */
  username: string;
};

export type AuthLoginSchemaWritable = {
  /**
   * The user's password (treated as a secret).
   */
  password: string;
  /**
   * The user's login name.
   */
  username: string;
};

export type BreadcrumbSchema = {
  id: number;
  name: string;
};

export type CountryListItemSchemaOut = {
  alpha2: string;
  best_name: string;
};

export type CsrfTokenOutSchema = {
  /**
   * The CSRF token used for session verification.
   */
  csrf_token: string;
};

export type FolderDetailSchemaOut = {
  breadcrumbs: Array<BreadcrumbSchema>;
  child_folders: Array<RootFolderSchemaOut>;
  /**
   * Timestamp when the object was created
   */
  created_at: string;
  description: string | null;
  /**
   * Groups allowed to edit this object
   */
  edit_groups?: Array<GroupSchemaOut>;
  folder_images: Array<number>;
  has_children: boolean;
  id: number;
  name: string;
  /**
   * Timestamp when the object was last updated
   */
  updated_at: string;
  /**
   * Groups allowed to view this object
   */
  view_groups?: Array<GroupSchemaOut>;
};

export type FolderUpdateSchemaIn = {
  description?: string | null;
  /**
   * New list of Group IDs allowed to edit
   */
  edit_group_ids?: Array<number> | null;
  name?: string | null;
  /**
   * New list of Group IDs allowed to view
   */
  view_group_ids?: Array<number> | null;
};

export type GroupCreateInSchema = {
  name: string;
};

export type GroupOutSchema = {
  id: number;
  name: string;
};

export type GroupSchemaOut = {
  /**
   * The unique identifier of the object
   */
  id: number;
  /**
   * The name of the group
   */
  name: string;
};

export type GroupUpdateInSchema = {
  name: string;
};

export type ImageDateSchemaOut = {
  date: string;
  day_valid: boolean;
  month_valid: boolean;
};

export type ImageDateUpdateSchemaIn = {
  date: string;
  day_valid: boolean;
  month_valid: boolean;
};

export type ImageFolderSchemaOut = {
  id: number;
  name: string;
};

export type ImageLocationSchemaOut = {
  city: string | null;
  country_code: string;
  country_name: string;
  sub_location: string | null;
  subdivision_code: string | null;
  subdivision_name: string | null;
};

export type ImageLocationUpdateSchemaIn = {
  city: string | null;
  country_code: string;
  sub_location: string | null;
  subdivision_code: string | null;
};

export type ImageMetadataSchemaOut = {
  can_edit: boolean;
  created_at: string;
  description: string | null;
  /**
   * Groups allowed to edit this object
   */
  edit_groups?: Array<GroupSchemaOut>;
  file_size: number;
  folder: ImageFolderSchemaOut;
  /**
   * The unique identifier of the object
   */
  id: number;
  image_fs_id: string;
  larger_size_url: string;
  orientation: RotationEnum;
  original_checksum: string;
  original_path: string;
  phash: string;
  size: ImageSizeSchemaOut;
  title: string;
  updated_at: string;
  /**
   * Groups allowed to view this object
   */
  view_groups?: Array<GroupSchemaOut>;
};

export type ImageMetadataUpdateSchemaIn = {
  description: string | null;
  /**
   * New list of Group IDs allowed to edit
   */
  edit_group_ids?: Array<number> | null;
  title: string | null;
  /**
   * New list of Group IDs allowed to view
   */
  view_group_ids?: Array<number> | null;
};

/**
 * IntEnum for the maximum side length of a scaled image,
 * commonly used for responsive image breakpoints.
 *
 * Sync with ImageScaledSideMaxChoices
 */
export type ImageScaledSideMaxEnum = 768 | 1024 | 1920 | 2560 | 3840;

export type ImageSizeSchemaOut = {
  large_version_height: number;
  large_version_width: number;
  original_height: number;
  original_width: number;
};

export type ImageThumbnailSchemaOut = {
  /**
   * The unique identifier of the object
   */
  id: number;
  thumbnail_height: number;
  thumbnail_url: string;
  thumbnail_width: number;
  title: string;
};

export type ImagesPerPageChoices = 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100;

export type Input = {
  limit?: number;
  offset?: number;
};

export type PagedAlbumBasicReadOutSchema = {
  count: number;
  items: Array<AlbumBasicReadOutSchema>;
};

export type PagedPersonImageOutSchema = {
  count: number;
  items: Array<PersonImageOutSchema>;
};

export type PagedPersonReadOutSchema = {
  count: number;
  items: Array<PersonReadOutSchema>;
};

export type PagedPetImageOutSchema = {
  count: number;
  items: Array<PetImageOutSchema>;
};

export type PagedPetReadSchemaOut = {
  count: number;
  items: Array<PetReadSchemaOut>;
};

export type PersonDetailOutSchema = {
  /**
   * Timestamp when the object was created
   */
  created_at: string;
  description?: string | null;
  /**
   * Groups allowed to edit this object
   */
  edit_groups?: Array<GroupSchemaOut>;
  id: number;
  image_count: number;
  name: string;
  /**
   * Timestamp when the object was last updated
   */
  updated_at: string;
  /**
   * Groups allowed to view this object
   */
  view_groups?: Array<GroupSchemaOut>;
};

export type PersonImageOutSchema = {
  /**
   * One image the person appears in
   */
  id: number;
};

/**
 * Schema for representing a PersonInImage instance.
 * Details a specific person's bounding box in an image.
 */
export type PersonInImageSchemaOut = {
  center_x: number;
  center_y: number;
  height: number;
  id: number;
  name: string;
  person_id: number;
  width: number;
};

/**
 * Schema when reading a person
 */
export type PersonReadOutSchema = {
  description?: string | null;
  id: number;
  image_count: number;
  name: string;
};

/**
 * Schema to update a person
 */
export type PersonUpdateInSchema = {
  description?: string | null;
  /**
   * New list of Group IDs allowed to edit
   */
  edit_group_ids?: Array<number> | null;
  name?: string | null;
  /**
   * New list of Group IDs allowed to view
   */
  view_group_ids?: Array<number> | null;
};

export type PetImageOutSchema = {
  /**
   * One image the pet appears in
   */
  id: number;
};

/**
 * Schema for representing a PetInImage instance.
 * Details a specific pet's bounding box in an image.
 */
export type PetInImageSchemaOut = {
  center_x: number;
  center_y: number;
  height: number;
  id: number;
  name: string;
  pet_id?: number | null;
  width: number;
};

/**
 * Schema when reading a pet
 */
export type PetReadDetailSchemaOut = {
  /**
   * Timestamp when the object was created
   */
  created_at: string;
  description?: string | null;
  /**
   * Groups allowed to edit this object
   */
  edit_groups?: Array<GroupSchemaOut>;
  id: number;
  name: string;
  pet_type?: PetTypeChoices | null;
  /**
   * Timestamp when the object was last updated
   */
  updated_at: string;
  /**
   * Groups allowed to view this object
   */
  view_groups?: Array<GroupSchemaOut>;
};

/**
 * Schema when reading a pet
 */
export type PetReadSchemaOut = {
  description?: string | null;
  id: number;
  image_count: number;
  name: string;
  pet_type?: PetTypeChoices | null;
};

export type PetTypeChoices = "cat" | "dog" | "horse";

/**
 * Schema to update a pet
 */
export type PetUpdateInSchema = {
  description?: string | null;
  /**
   * New list of Group IDs allowed to edit
   */
  edit_group_ids?: Array<number> | null;
  name?: string | null;
  pet_type?: PetTypeChoices | null;
  /**
   * New list of Group IDs allowed to view
   */
  view_group_ids?: Array<number> | null;
};

export type RootFolderSchemaOut = {
  child_count?: number;
  description: string | null;
  /**
   * Groups allowed to edit this object
   */
  edit_groups?: Array<GroupSchemaOut>;
  id: number;
  image_count?: number;
  name: string;
  /**
   * Groups allowed to view this object
   */
  view_groups?: Array<GroupSchemaOut>;
};

/**
 * https://exiftool.org/TagNames/EXIF.html (0x0112)
 */
export type RotationEnum = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

/**
 * Schema for outputting site-wide image and quality settings.
 * Used for retrieving the current configuration.
 */
export type SiteSettingsSchemaOut = {
  /**
   * The largest side dimension of generated large images
   */
  large_image_max_size: ImageScaledSideMaxEnum;
  /**
   * The WebP quality setting for generate large images
   */
  large_image_quality: number;
  /**
   * The largest side dimension of generated image thumbnails
   */
  thumbnail_max_size: ThumbnailSizeEnum;
};

/**
 * Schema for updating site settings. All fields are optional to allow
 * partial updates (PATCH requests), using Python 3.10+ `| None` syntax.
 */
export type SiteSettingsUpdateSchemaIn = {
  /**
   * The largest side dimension of generated large images
   */
  large_image_max_size?: ImageScaledSideMaxEnum | null;
  /**
   * The WebP quality setting for generate large images
   */
  large_image_quality?: number | null;
  /**
   * The largest side dimension of generated image thumbnails
   */
  thumbnail_max_size?: ThumbnailSizeEnum | null;
};

/**
 * Combined schema for system and user-specific statistics.
 */
export type StatisticsResponseSchema = {
  /**
   * Overall system-level statistics, such as disk usage.
   */
  system_statistics: SystemStatisticsSchema;
  /**
   * Statistics related to the current user's view and edit permissions.
   */
  user_statistics: UserStatisticsSchema;
};

export type SubdivisionListItemSchemaOut = {
  code: string;
  name: string;
};

/**
 * Schema for overall system statistics.
 * This now only includes non-sensitive system-level information like disk space.
 */
export type SystemStatisticsSchema = {
  /**
   * Disk space currently free in GB where media files are stored.
   */
  disk_free_space_gb?: number | null;
  /**
   * Total disk space available in GB where media files are stored.
   */
  disk_total_space_gb?: number | null;
  /**
   * Disk space currently used in GB where media files are stored.
   */
  disk_used_space_gb?: number | null;
};

/**
 * Defines standard pixel dimensions for image thumbnails using an IntEnum.
 * The value represents the maximum dimension (width or height)
 * of the thumbnail, with aspect ratio preserved.
 *
 * Sync with ThumbnailSizeChoices
 */
export type ThumbnailSizeEnum = 128 | 256 | 512 | 640 | 800;

export type TimezoneChoices =
  | "Africa/Abidjan"
  | "Africa/Accra"
  | "Africa/Addis_Ababa"
  | "Africa/Algiers"
  | "Africa/Asmara"
  | "Africa/Asmera"
  | "Africa/Bamako"
  | "Africa/Bangui"
  | "Africa/Banjul"
  | "Africa/Bissau"
  | "Africa/Blantyre"
  | "Africa/Brazzaville"
  | "Africa/Bujumbura"
  | "Africa/Cairo"
  | "Africa/Casablanca"
  | "Africa/Ceuta"
  | "Africa/Conakry"
  | "Africa/Dakar"
  | "Africa/Dar_es_Salaam"
  | "Africa/Djibouti"
  | "Africa/Douala"
  | "Africa/El_Aaiun"
  | "Africa/Freetown"
  | "Africa/Gaborone"
  | "Africa/Harare"
  | "Africa/Johannesburg"
  | "Africa/Juba"
  | "Africa/Kampala"
  | "Africa/Khartoum"
  | "Africa/Kigali"
  | "Africa/Kinshasa"
  | "Africa/Lagos"
  | "Africa/Libreville"
  | "Africa/Lome"
  | "Africa/Luanda"
  | "Africa/Lubumbashi"
  | "Africa/Lusaka"
  | "Africa/Malabo"
  | "Africa/Maputo"
  | "Africa/Maseru"
  | "Africa/Mbabane"
  | "Africa/Mogadishu"
  | "Africa/Monrovia"
  | "Africa/Nairobi"
  | "Africa/Ndjamena"
  | "Africa/Niamey"
  | "Africa/Nouakchott"
  | "Africa/Ouagadougou"
  | "Africa/Porto-Novo"
  | "Africa/Sao_Tome"
  | "Africa/Timbuktu"
  | "Africa/Tripoli"
  | "Africa/Tunis"
  | "Africa/Windhoek"
  | "America/Adak"
  | "America/Anchorage"
  | "America/Anguilla"
  | "America/Antigua"
  | "America/Araguaina"
  | "America/Argentina/Buenos_Aires"
  | "America/Argentina/Catamarca"
  | "America/Argentina/ComodRivadavia"
  | "America/Argentina/Cordoba"
  | "America/Argentina/Jujuy"
  | "America/Argentina/La_Rioja"
  | "America/Argentina/Mendoza"
  | "America/Argentina/Rio_Gallegos"
  | "America/Argentina/Salta"
  | "America/Argentina/San_Juan"
  | "America/Argentina/San_Luis"
  | "America/Argentina/Tucuman"
  | "America/Argentina/Ushuaia"
  | "America/Aruba"
  | "America/Asuncion"
  | "America/Atikokan"
  | "America/Atka"
  | "America/Bahia"
  | "America/Bahia_Banderas"
  | "America/Barbados"
  | "America/Belem"
  | "America/Belize"
  | "America/Blanc-Sablon"
  | "America/Boa_Vista"
  | "America/Bogota"
  | "America/Boise"
  | "America/Buenos_Aires"
  | "America/Cambridge_Bay"
  | "America/Campo_Grande"
  | "America/Cancun"
  | "America/Caracas"
  | "America/Catamarca"
  | "America/Cayenne"
  | "America/Cayman"
  | "America/Chicago"
  | "America/Chihuahua"
  | "America/Ciudad_Juarez"
  | "America/Coral_Harbour"
  | "America/Cordoba"
  | "America/Costa_Rica"
  | "America/Coyhaique"
  | "America/Creston"
  | "America/Cuiaba"
  | "America/Curacao"
  | "America/Danmarkshavn"
  | "America/Dawson"
  | "America/Dawson_Creek"
  | "America/Denver"
  | "America/Detroit"
  | "America/Dominica"
  | "America/Edmonton"
  | "America/Eirunepe"
  | "America/El_Salvador"
  | "America/Ensenada"
  | "America/Fort_Nelson"
  | "America/Fort_Wayne"
  | "America/Fortaleza"
  | "America/Glace_Bay"
  | "America/Godthab"
  | "America/Goose_Bay"
  | "America/Grand_Turk"
  | "America/Grenada"
  | "America/Guadeloupe"
  | "America/Guatemala"
  | "America/Guayaquil"
  | "America/Guyana"
  | "America/Halifax"
  | "America/Havana"
  | "America/Hermosillo"
  | "America/Indiana/Indianapolis"
  | "America/Indiana/Knox"
  | "America/Indiana/Marengo"
  | "America/Indiana/Petersburg"
  | "America/Indiana/Tell_City"
  | "America/Indiana/Vevay"
  | "America/Indiana/Vincennes"
  | "America/Indiana/Winamac"
  | "America/Indianapolis"
  | "America/Inuvik"
  | "America/Iqaluit"
  | "America/Jamaica"
  | "America/Jujuy"
  | "America/Juneau"
  | "America/Kentucky/Louisville"
  | "America/Kentucky/Monticello"
  | "America/Knox_IN"
  | "America/Kralendijk"
  | "America/La_Paz"
  | "America/Lima"
  | "America/Los_Angeles"
  | "America/Louisville"
  | "America/Lower_Princes"
  | "America/Maceio"
  | "America/Managua"
  | "America/Manaus"
  | "America/Marigot"
  | "America/Martinique"
  | "America/Matamoros"
  | "America/Mazatlan"
  | "America/Mendoza"
  | "America/Menominee"
  | "America/Merida"
  | "America/Metlakatla"
  | "America/Mexico_City"
  | "America/Miquelon"
  | "America/Moncton"
  | "America/Monterrey"
  | "America/Montevideo"
  | "America/Montreal"
  | "America/Montserrat"
  | "America/Nassau"
  | "America/New_York"
  | "America/Nipigon"
  | "America/Nome"
  | "America/Noronha"
  | "America/North_Dakota/Beulah"
  | "America/North_Dakota/Center"
  | "America/North_Dakota/New_Salem"
  | "America/Nuuk"
  | "America/Ojinaga"
  | "America/Panama"
  | "America/Pangnirtung"
  | "America/Paramaribo"
  | "America/Phoenix"
  | "America/Port-au-Prince"
  | "America/Port_of_Spain"
  | "America/Porto_Acre"
  | "America/Porto_Velho"
  | "America/Puerto_Rico"
  | "America/Punta_Arenas"
  | "America/Rainy_River"
  | "America/Rankin_Inlet"
  | "America/Recife"
  | "America/Regina"
  | "America/Resolute"
  | "America/Rio_Branco"
  | "America/Rosario"
  | "America/Santa_Isabel"
  | "America/Santarem"
  | "America/Santiago"
  | "America/Santo_Domingo"
  | "America/Sao_Paulo"
  | "America/Scoresbysund"
  | "America/Shiprock"
  | "America/Sitka"
  | "America/St_Barthelemy"
  | "America/St_Johns"
  | "America/St_Kitts"
  | "America/St_Lucia"
  | "America/St_Thomas"
  | "America/St_Vincent"
  | "America/Swift_Current"
  | "America/Tegucigalpa"
  | "America/Thule"
  | "America/Thunder_Bay"
  | "America/Tijuana"
  | "America/Toronto"
  | "America/Tortola"
  | "America/Vancouver"
  | "America/Virgin"
  | "America/Whitehorse"
  | "America/Winnipeg"
  | "America/Yakutat"
  | "America/Yellowknife"
  | "Antarctica/Casey"
  | "Antarctica/Davis"
  | "Antarctica/DumontDUrville"
  | "Antarctica/Macquarie"
  | "Antarctica/Mawson"
  | "Antarctica/McMurdo"
  | "Antarctica/Palmer"
  | "Antarctica/Rothera"
  | "Antarctica/South_Pole"
  | "Antarctica/Syowa"
  | "Antarctica/Troll"
  | "Antarctica/Vostok"
  | "Arctic/Longyearbyen";

export type UserGroupAssignInSchema = {
  id: number;
};

export type UserInCreateSchemaReadable = {
  email?: string | null;
  first_name?: string | null;
  is_active?: boolean;
  is_staff?: boolean;
  is_superuser?: boolean;
  last_name?: string | null;
  username: string;
};

export type UserInCreateSchemaWritable = {
  email?: string | null;
  first_name?: string | null;
  is_active?: boolean;
  is_staff?: boolean;
  is_superuser?: boolean;
  last_name?: string | null;
  password: string;
  username: string;
};

export type UserOutSchema = {
  email?: string | null;
  first_name: string;
  id: number;
  is_active?: boolean;
  is_staff?: boolean;
  is_superuser?: boolean;
  last_name: string;
  username: string;
};

export type UserProfileOutSchema = {
  bio: string | null;
  items_per_page: ImagesPerPageChoices;
  timezone_name: TimezoneChoices;
};

export type UserProfileUpdateSchema = {
  bio?: string | null;
  items_per_page?: ImagesPerPageChoices | null;
  timezone_name?: TimezoneChoices | null;
};

/**
 * Schema for user-specific statistics.
 */
export type UserStatisticsSchema = {
  /**
   * Total number of albums the current user can edit.
   */
  total_albums_editable: number;
  /**
   * Total number of albums the current user can view.
   */
  total_albums_viewable: number;
  /**
   * Total number of image folders the current user can edit.
   */
  total_folders_editable: number;
  /**
   * Total number of image folders the current user can view.
   */
  total_folders_viewable: number;
  /**
   * Total number of images the current user can edit.
   */
  total_images_editable: number;
  /**
   * Total number of images the current user can view.
   */
  total_images_viewable: number;
  /**
   * Total number of people the current user can edit.
   */
  total_people_editable: number;
  /**
   * Total number of people the current user can view.
   */
  total_people_viewable: number;
  /**
   * Total number of pets the current user can edit.
   */
  total_pets_editable: number;
  /**
   * Total number of pets the current user can view.
   */
  total_pets_viewable: number;
  /**
   * Total number of rough dates the current user can view.
   */
  total_rough_dates: number;
  /**
   * Total number of rough locations the current user can view.
   */
  total_rough_locations: number;
  /**
   * Total number of image sources the current user can edit.
   */
  total_sources_editable: number;
  /**
   * Total number of image sources the current user can view.
   */
  total_sources_viewable: number;
  /**
   * Total number of tags in the system
   */
  total_tags: number;
};

export type UserUpdateInSchemeReadable = {
  email?: string | null;
  first_name?: string | null;
  is_active?: boolean | null;
  is_staff?: boolean | null;
  is_superuser?: boolean | null;
  last_name?: string | null;
  password?: string | null;
};

export type UserUpdateInSchemeWritable = {
  email?: string | null;
  first_name?: string | null;
  is_active?: boolean | null;
  is_staff?: boolean | null;
  is_superuser?: boolean | null;
  last_name?: string | null;
  password?: string | null;
};

export type GetAllAlbumsData = {
  body?: never;
  path?: never;
  query?: {
    album_name?: string | null;
    limit?: number;
    offset?: number;
  };
  url: "/api/album/";
};

export type GetAllAlbumsResponses = {
  /**
   * OK
   */
  200: PagedAlbumBasicReadOutSchema;
};

export type GetAllAlbumsResponse = GetAllAlbumsResponses[keyof GetAllAlbumsResponses];

export type CreateAlbumData = {
  body: AlbumCreateInSchema;
  path?: never;
  query?: never;
  url: "/api/album/";
};

export type CreateAlbumResponses = {
  /**
   * Created
   */
  201: AlbumBasicReadOutSchema;
};

export type CreateAlbumResponse = CreateAlbumResponses[keyof CreateAlbumResponses];

export type DeleteAlbumData = {
  body?: never;
  path: {
    album_id: number;
  };
  query?: never;
  url: "/api/album/{album_id}/";
};

export type DeleteAlbumResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAlbumResponse = DeleteAlbumResponses[keyof DeleteAlbumResponses];

export type GetSingleAlbumInfoData = {
  body?: never;
  path: {
    album_id: number;
  };
  query?: never;
  url: "/api/album/{album_id}/";
};

export type GetSingleAlbumInfoErrors = {
  /**
   * Album not found or inaccessible
   */
  404: unknown;
};

export type GetSingleAlbumInfoResponses = {
  /**
   * OK
   */
  200: AlbumWithImagesOutSchema;
};

export type GetSingleAlbumInfoResponse =
  GetSingleAlbumInfoResponses[keyof GetSingleAlbumInfoResponses];

export type UpdateAlbumInfoData = {
  body: AlbumUpdateInSchema;
  path: {
    album_id: number;
  };
  query?: never;
  url: "/api/album/{album_id}/";
};

export type UpdateAlbumInfoErrors = {
  /**
   * Album not found or inaccessible
   */
  404: unknown;
};

export type UpdateAlbumInfoResponses = {
  /**
   * OK
   */
  200: AlbumBasicReadOutSchema;
};

export type UpdateAlbumInfoResponse = UpdateAlbumInfoResponses[keyof UpdateAlbumInfoResponses];

export type AddImageToAlbumData = {
  body: AlbumAddImageInSchema;
  path: {
    album_id: number;
  };
  query?: never;
  url: "/api/album/{album_id}/add/";
};

export type AddImageToAlbumResponses = {
  /**
   * OK
   */
  200: AlbumWithImagesOutSchema;
};

export type AddImageToAlbumResponse = AddImageToAlbumResponses[keyof AddImageToAlbumResponses];

export type DownloadAlbumData = {
  body?: never;
  path: {
    album_id: number;
  };
  query?: {
    zip_originals?: boolean;
  };
  url: "/api/album/{album_id}/download/";
};

export type DownloadAlbumResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteImageFromAlbumData = {
  body: AlbumRemoveImageInSchema;
  path: {
    album_id: number;
  };
  query?: never;
  url: "/api/album/{album_id}/remove/";
};

export type DeleteImageFromAlbumResponses = {
  /**
   * OK
   */
  200: AlbumWithImagesOutSchema;
};

export type DeleteImageFromAlbumResponse =
  DeleteImageFromAlbumResponses[keyof DeleteImageFromAlbumResponses];

export type UpdateAlbumSortingData = {
  body: AlbumSortUpdateInSchema;
  path: {
    album_id: number;
  };
  query?: never;
  url: "/api/album/{album_id}/sort/";
};

export type UpdateAlbumSortingErrors = {
  /**
   * Sorting list mismatch with album contents
   */
  400: unknown;
  /**
   * Album not found or inaccessible
   */
  404: unknown;
};

export type UpdateAlbumSortingResponses = {
  /**
   * OK
   */
  200: AlbumWithImagesOutSchema;
};

export type UpdateAlbumSortingResponse =
  UpdateAlbumSortingResponses[keyof UpdateAlbumSortingResponses];

export type AuthGetCsrfTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/csrf/";
};

export type AuthGetCsrfTokenResponses = {
  /**
   * OK
   */
  200: CsrfTokenOutSchema;
};

export type AuthGetCsrfTokenResponse = AuthGetCsrfTokenResponses[keyof AuthGetCsrfTokenResponses];

export type AuthLoginData = {
  body: AuthLoginSchemaWritable;
  path?: never;
  query?: never;
  url: "/api/auth/login/";
};

export type AuthLoginErrors = {
  /**
   * username or password not provided
   */
  400: unknown;
  /**
   * invalid username or password provided
   */
  401: unknown;
};

export type AuthLoginResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/logout/";
};

export type AuthLogoutResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type FolderListRootsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/folder/";
};

export type FolderListRootsResponses = {
  /**
   * OK
   */
  200: Array<RootFolderSchemaOut>;
};

export type FolderListRootsResponse = FolderListRootsResponses[keyof FolderListRootsResponses];

export type FolderGetDetailsData = {
  body?: never;
  path: {
    folder_id: number;
  };
  query?: never;
  url: "/api/folder/{folder_id}/";
};

export type FolderGetDetailsResponses = {
  /**
   * OK
   */
  200: FolderDetailSchemaOut;
};

export type FolderGetDetailsResponse = FolderGetDetailsResponses[keyof FolderGetDetailsResponses];

export type UpdateFolderInfoData = {
  body: FolderUpdateSchemaIn;
  path: {
    folder_id: number;
  };
  query?: never;
  url: "/api/folder/{folder_id}/";
};

export type UpdateFolderInfoResponses = {
  /**
   * OK
   */
  200: FolderDetailSchemaOut;
};

export type UpdateFolderInfoResponse = UpdateFolderInfoResponses[keyof UpdateFolderInfoResponses];

export type GroupGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/groups/";
};

export type GroupGetAllResponses = {
  /**
   * OK
   */
  200: Array<GroupOutSchema>;
};

export type GroupGetAllResponse = GroupGetAllResponses[keyof GroupGetAllResponses];

export type GroupsCreateData = {
  body: GroupCreateInSchema | Array<GroupCreateInSchema>;
  path?: never;
  query?: never;
  url: "/api/groups/";
};

export type GroupsCreateResponses = {
  /**
   * OK
   */
  200: Array<GroupOutSchema>;
};

export type GroupsCreateResponse = GroupsCreateResponses[keyof GroupsCreateResponses];

export type GroupDeleteSingleData = {
  body?: never;
  path: {
    group_id: number;
  };
  query?: never;
  url: "/api/groups/{group_id}/";
};

export type GroupDeleteSingleResponses = {
  /**
   * No Content
   */
  204: void;
};

export type GroupDeleteSingleResponse =
  GroupDeleteSingleResponses[keyof GroupDeleteSingleResponses];

export type GroupGetSingleData = {
  body?: never;
  path: {
    group_id: number;
  };
  query?: never;
  url: "/api/groups/{group_id}/";
};

export type GroupGetSingleResponses = {
  /**
   * OK
   */
  200: GroupOutSchema;
};

export type GroupGetSingleResponse = GroupGetSingleResponses[keyof GroupGetSingleResponses];

export type GroupUpdateSingleData = {
  body: GroupUpdateInSchema;
  path: {
    group_id: number;
  };
  query?: never;
  url: "/api/groups/{group_id}/";
};

export type GroupUpdateSingleResponses = {
  /**
   * OK
   */
  200: GroupOutSchema;
};

export type GroupUpdateSingleResponse =
  GroupUpdateSingleResponses[keyof GroupUpdateSingleResponses];

export type ImageGetDateData = {
  body?: never;
  path: {
    image_id: number;
  };
  query?: never;
  url: "/api/image/{image_id}/date/";
};

export type ImageGetDateErrors = {
  /**
   * The user does not have permissions for this image
   */
  401: unknown;
  /**
   * The image does not exist
   */
  404: unknown;
};

export type ImageGetDateResponses = {
  /**
   * OK
   */
  200: ImageDateSchemaOut;
  /**
   * The image has no date
   */
  204: void;
};

export type ImageGetDateResponse = ImageGetDateResponses[keyof ImageGetDateResponses];

export type ImageUpdateDateData = {
  body: ImageDateUpdateSchemaIn;
  path: {
    image_id: number;
  };
  query?: never;
  url: "/api/image/{image_id}/date/";
};

export type ImageUpdateDateErrors = {
  /**
   * The user does not have permissions for this image
   */
  401: unknown;
  /**
   * The image does not exist
   */
  404: unknown;
};

export type ImageUpdateDateResponses = {
  /**
   * OK
   */
  200: ImageDateSchemaOut;
};

export type ImageUpdateDateResponse = ImageUpdateDateResponses[keyof ImageUpdateDateResponses];

export type ImageGetLocationData = {
  body?: never;
  path: {
    image_id: number;
  };
  query?: never;
  url: "/api/image/{image_id}/location/";
};

export type ImageGetLocationErrors = {
  /**
   * The user does not have permissions for this image
   */
  401: unknown;
  /**
   * The image does not exist
   */
  404: unknown;
};

export type ImageGetLocationResponses = {
  /**
   * OK
   */
  200: ImageLocationSchemaOut;
  /**
   * The image has no location
   */
  204: void;
};

export type ImageGetLocationResponse = ImageGetLocationResponses[keyof ImageGetLocationResponses];

export type ImageUpdateLocationData = {
  body: ImageLocationUpdateSchemaIn;
  path: {
    image_id: number;
  };
  query?: never;
  url: "/api/image/{image_id}/location/";
};

export type ImageUpdateLocationErrors = {
  /**
   * The country is not found or subdivision is not in the country
   */
  400: unknown;
  /**
   * The user does not have permissions for this image
   */
  401: unknown;
  /**
   * The image does not exist
   */
  404: unknown;
};

export type ImageUpdateLocationResponses = {
  /**
   * OK
   */
  200: ImageLocationSchemaOut;
};

export type ImageUpdateLocationResponse =
  ImageUpdateLocationResponses[keyof ImageUpdateLocationResponses];

export type ImageGetMetadataData = {
  body?: never;
  path: {
    image_id: number;
  };
  query?: never;
  url: "/api/image/{image_id}/metadata/";
};

export type ImageGetMetadataResponses = {
  /**
   * OK
   */
  200: ImageMetadataSchemaOut;
};

export type ImageGetMetadataResponse = ImageGetMetadataResponses[keyof ImageGetMetadataResponses];

export type ImageUpdateMetadataData = {
  body: ImageMetadataUpdateSchemaIn;
  path: {
    image_id: number;
  };
  query?: never;
  url: "/api/image/{image_id}/metadata/";
};

export type ImageUpdateMetadataResponses = {
  /**
   * OK
   */
  200: ImageMetadataSchemaOut;
};

export type ImageUpdateMetadataResponse =
  ImageUpdateMetadataResponses[keyof ImageUpdateMetadataResponses];

export type ImageGetPeopleData = {
  body?: never;
  path: {
    image_id: number;
  };
  query?: never;
  url: "/api/image/{image_id}/people/";
};

export type ImageGetPeopleResponses = {
  /**
   * OK
   */
  200: Array<PersonInImageSchemaOut>;
};

export type ImageGetPeopleResponse = ImageGetPeopleResponses[keyof ImageGetPeopleResponses];

export type ImageGetPetsData = {
  body?: never;
  path: {
    image_id: number;
  };
  query?: never;
  url: "/api/image/{image_id}/pets/";
};

export type ImageGetPetsResponses = {
  /**
   * OK
   */
  200: Array<PetInImageSchemaOut>;
};

export type ImageGetPetsResponse = ImageGetPetsResponses[keyof ImageGetPetsResponses];

export type ImageGetThumbInfoData = {
  body?: never;
  path: {
    image_id: number;
  };
  query?: never;
  url: "/api/image/{image_id}/thumbnail/";
};

export type ImageGetThumbInfoResponses = {
  /**
   * OK
   */
  200: ImageThumbnailSchemaOut;
};

export type ImageGetThumbInfoResponse =
  ImageGetThumbInfoResponses[keyof ImageGetThumbInfoResponses];

export type LocationGetCitiesData = {
  body?: never;
  path?: never;
  query: {
    country_code: string;
    subdivision_code?: string | null;
  };
  url: "/api/location/cities/";
};

export type LocationGetCitiesResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type LocationGetCitiesResponse =
  LocationGetCitiesResponses[keyof LocationGetCitiesResponses];

export type LocationGetCountriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/location/countries/";
};

export type LocationGetCountriesResponses = {
  /**
   * OK
   */
  200: Array<CountryListItemSchemaOut>;
};

export type LocationGetCountriesResponse =
  LocationGetCountriesResponses[keyof LocationGetCountriesResponses];

export type LocationGetSubdivisionsData = {
  body?: never;
  path?: never;
  query: {
    country_code: string;
  };
  url: "/api/location/subdivisions/";
};

export type LocationGetSubdivisionsResponses = {
  /**
   * OK
   */
  200: Array<SubdivisionListItemSchemaOut>;
};

export type LocationGetSubdivisionsResponse =
  LocationGetSubdivisionsResponses[keyof LocationGetSubdivisionsResponses];

export type LocationGetSubLocationsData = {
  body?: never;
  path?: never;
  query: {
    country_code: string;
    city_name: string;
    subdivision_code?: string | null;
  };
  url: "/api/location/sublocations/";
};

export type LocationGetSubLocationsResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type LocationGetSubLocationsResponse =
  LocationGetSubLocationsResponses[keyof LocationGetSubLocationsResponses];

export type GetAllPeopleData = {
  body?: never;
  path?: never;
  query?: {
    sort_by?: string;
    person_name?: string | null;
    limit?: number;
    offset?: number;
  };
  url: "/api/person/";
};

export type GetAllPeopleResponses = {
  /**
   * OK
   */
  200: PagedPersonReadOutSchema;
};

export type GetAllPeopleResponse = GetAllPeopleResponses[keyof GetAllPeopleResponses];

export type GetPersonDetailData = {
  body?: never;
  path: {
    person_id: number;
  };
  query?: never;
  url: "/api/person/{person_id}/";
};

export type GetPersonDetailResponses = {
  /**
   * OK
   */
  200: PersonDetailOutSchema;
};

export type GetPersonDetailResponse = GetPersonDetailResponses[keyof GetPersonDetailResponses];

export type UpdatePersonDetailData = {
  body: PersonUpdateInSchema;
  path: {
    person_id: number;
  };
  query?: never;
  url: "/api/person/{person_id}/";
};

export type UpdatePersonDetailResponses = {
  /**
   * OK
   */
  200: PersonDetailOutSchema;
};

export type UpdatePersonDetailResponse =
  UpdatePersonDetailResponses[keyof UpdatePersonDetailResponses];

export type GetPersonImagesData = {
  body?: never;
  path: {
    person_id: number;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: "/api/person/{person_id}/images/";
};

export type GetPersonImagesResponses = {
  /**
   * OK
   */
  200: PagedPersonImageOutSchema;
};

export type GetPersonImagesResponse = GetPersonImagesResponses[keyof GetPersonImagesResponses];

export type GetAllPetsData = {
  body?: never;
  path?: never;
  query?: {
    sort_by?: string;
    pet_name?: string | null;
    pet_type?: PetTypeChoices | null;
    limit?: number;
    offset?: number;
  };
  url: "/api/pet/";
};

export type GetAllPetsResponses = {
  /**
   * OK
   */
  200: PagedPetReadSchemaOut;
};

export type GetAllPetsResponse = GetAllPetsResponses[keyof GetAllPetsResponses];

export type GetPetDetailData = {
  body?: never;
  path: {
    pet_id: number;
  };
  query?: never;
  url: "/api/pet/{pet_id}/";
};

export type GetPetDetailErrors = {
  /**
   * Not Found Response
   */
  404: unknown;
};

export type GetPetDetailResponses = {
  /**
   * OK
   */
  200: PetReadDetailSchemaOut;
};

export type GetPetDetailResponse = GetPetDetailResponses[keyof GetPetDetailResponses];

export type UpdatePetData = {
  body: PetUpdateInSchema;
  path: {
    pet_id: number;
  };
  query?: never;
  url: "/api/pet/{pet_id}/";
};

export type UpdatePetErrors = {
  /**
   * Not Found Response
   */
  404: unknown;
};

export type UpdatePetResponses = {
  /**
   * OK
   */
  200: PetReadDetailSchemaOut;
};

export type UpdatePetResponse = UpdatePetResponses[keyof UpdatePetResponses];

export type GetPetImagesData = {
  body?: never;
  path: {
    pet_id: number;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: "/api/pet/{pet_id}/images/";
};

export type GetPetImagesResponses = {
  /**
   * OK
   */
  200: PagedPetImageOutSchema;
};

export type GetPetImagesResponse = GetPetImagesResponses[keyof GetPetImagesResponses];

export type GetSystemSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/system/settings/";
};

export type GetSystemSettingsResponses = {
  /**
   * OK
   */
  200: SiteSettingsSchemaOut;
};

export type GetSystemSettingsResponse =
  GetSystemSettingsResponses[keyof GetSystemSettingsResponses];

export type UpdateSystemSettingsData = {
  body: SiteSettingsUpdateSchemaIn;
  path?: never;
  query?: never;
  url: "/api/system/settings/";
};

export type UpdateSystemSettingsResponses = {
  /**
   * OK
   */
  200: SiteSettingsSchemaOut;
};

export type UpdateSystemSettingsResponse =
  UpdateSystemSettingsResponses[keyof UpdateSystemSettingsResponses];

export type GetSystemStatisticsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/system/statistics/";
};

export type GetSystemStatisticsResponses = {
  /**
   * OK
   */
  200: StatisticsResponseSchema;
};

export type GetSystemStatisticsResponse =
  GetSystemStatisticsResponses[keyof GetSystemStatisticsResponses];

export type UserGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/user/";
};

export type UserGetAllResponses = {
  /**
   * OK
   */
  200: Array<UserOutSchema>;
};

export type UserGetAllResponse = UserGetAllResponses[keyof UserGetAllResponses];

export type UserCreateData = {
  body: UserInCreateSchemaWritable;
  path?: never;
  query?: never;
  url: "/api/user/";
};

export type UserCreateResponses = {
  /**
   * OK
   */
  200: UserOutSchema;
};

export type UserCreateResponse = UserCreateResponses[keyof UserCreateResponses];

export type UserGetMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/user/me/";
};

export type UserGetMeResponses = {
  /**
   * OK
   */
  200: UserOutSchema;
};

export type UserGetMeResponse = UserGetMeResponses[keyof UserGetMeResponses];

export type UserGetMyProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/user/me/profile/";
};

export type UserGetMyProfileResponses = {
  /**
   * OK
   */
  200: UserProfileOutSchema;
};

export type UserGetMyProfileResponse = UserGetMyProfileResponses[keyof UserGetMyProfileResponses];

export type UserGetGroupsData = {
  body?: never;
  path: {
    user_id: number;
  };
  query?: never;
  url: "/api/user/{user_id}/groups/";
};

export type UserGetGroupsResponses = {
  /**
   * OK
   */
  200: Array<GroupOutSchema>;
};

export type UserGetGroupsResponse = UserGetGroupsResponses[keyof UserGetGroupsResponses];

export type UserSetGroupsData = {
  body: Array<UserGroupAssignInSchema>;
  path: {
    user_id: number;
  };
  query?: never;
  url: "/api/user/{user_id}/groups/";
};

export type UserSetGroupsErrors = {
  /**
   * some provided groups don't exist
   */
  400: unknown;
};

export type UserSetGroupsResponses = {
  /**
   * OK
   */
  200: Array<GroupOutSchema>;
};

export type UserSetGroupsResponse = UserSetGroupsResponses[keyof UserSetGroupsResponses];

export type UserGetInfoData = {
  body?: never;
  path: {
    user_id: number;
  };
  query?: never;
  url: "/api/user/{user_id}/info/";
};

export type UserGetInfoResponses = {
  /**
   * OK
   */
  200: UserOutSchema;
};

export type UserGetInfoResponse = UserGetInfoResponses[keyof UserGetInfoResponses];

export type UserSetInfoData = {
  body: UserUpdateInSchemeWritable;
  path: {
    user_id: number;
  };
  query?: never;
  url: "/api/user/{user_id}/info/";
};

export type UserSetInfoResponses = {
  /**
   * OK
   */
  200: UserOutSchema;
};

export type UserSetInfoResponse = UserSetInfoResponses[keyof UserSetInfoResponses];

export type UserGetProfileData = {
  body?: never;
  path: {
    user_id: number;
  };
  query?: never;
  url: "/api/user/{user_id}/profile/";
};

export type UserGetProfileResponses = {
  /**
   * OK
   */
  200: UserProfileOutSchema;
};

export type UserGetProfileResponse = UserGetProfileResponses[keyof UserGetProfileResponses];

export type UserEditProfileData = {
  body: UserProfileUpdateSchema;
  path: {
    user_id: number;
  };
  query?: never;
  url: "/api/user/{user_id}/profile/";
};

export type UserEditProfileResponses = {
  /**
   * OK
   */
  200: UserProfileOutSchema;
};

export type UserEditProfileResponse = UserEditProfileResponses[keyof UserEditProfileResponses];

export type ClientOptions = {
  baseURL: string;
};
