#!/command/with-contenv /bin/ash
# shellcheck shell=bash
declare -r log_prefix="[init-user]"


usermap_original_uid=$(id -u memoria)
usermap_original_gid=$(id -g memoria)
usermap_new_uid=${PUID:-$usermap_original_uid}
usermap_new_gid=${PGUID:-${usermap_original_gid:-$usermap_new_uid}}

if [[ ${usermap_new_uid} != "${usermap_original_uid}" ]]; then
	echo "${log_prefix} Mapping UID for memoria to $usermap_new_uid"
    usermod -o -u "${usermap_new_uid}" memoria
else
	echo "${log_prefix} No UID changes for memoria"
fi

if [[ ${usermap_new_gid} != "${usermap_original_gid}" ]]; then
	echo "${log_prefix} Mapping GID for memoria to $usermap_new_gid"
    groupmod -o -g "${usermap_new_gid}" memoria
else
	echo "${log_prefix} No GID changes for memoria"
fi
