# Generated by Django 5.2 on 2025-05-05 22:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("memoria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
