# Generated by Django 5.2 on 2025-05-01 16:48

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memoria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="America/Los_Angeles"),
        ),
    ]
