# Generated by Django 5.2 on 2025-05-06 16:18

import django.db.models.expressions
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("memoria", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="personinimage",
            name="height_percent_value",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(models.F("height"), "*", models.Value(100)),
                output_field=models.FloatField(),
                verbose_name="Height in percent",
            ),
        ),
        migrations.AddField(
            model_name="personinimage",
            name="left_percent_value",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        models.F("center_x"),
                        "-",
                        django.db.models.expressions.CombinedExpression(models.F("width"), "/", models.Value(2)),
                    ),
                    "*",
                    models.Value(100),
                ),
                output_field=models.FloatField(),
                verbose_name="Left position in percent",
            ),
        ),
        migrations.AddField(
            model_name="personinimage",
            name="top_percent_value",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        models.F("center_y"),
                        "-",
                        django.db.models.expressions.CombinedExpression(models.F("height"), "/", models.Value(2)),
                    ),
                    "*",
                    models.Value(100),
                ),
                output_field=models.FloatField(),
                verbose_name="Top position in percent",
            ),
        ),
        migrations.AddField(
            model_name="personinimage",
            name="width_percent_value",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(models.F("width"), "*", models.Value(100)),
                output_field=models.FloatField(),
                verbose_name="Width in percent",
            ),
        ),
        migrations.AddField(
            model_name="petinimage",
            name="height_percent_value",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(models.F("height"), "*", models.Value(100)),
                output_field=models.FloatField(),
                verbose_name="Height in percent",
            ),
        ),
        migrations.AddField(
            model_name="petinimage",
            name="left_percent_value",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        models.F("center_x"),
                        "-",
                        django.db.models.expressions.CombinedExpression(models.F("width"), "/", models.Value(2)),
                    ),
                    "*",
                    models.Value(100),
                ),
                output_field=models.FloatField(),
                verbose_name="Left position in percent",
            ),
        ),
        migrations.AddField(
            model_name="petinimage",
            name="top_percent_value",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        models.F("center_y"),
                        "-",
                        django.db.models.expressions.CombinedExpression(models.F("height"), "/", models.Value(2)),
                    ),
                    "*",
                    models.Value(100),
                ),
                output_field=models.FloatField(),
                verbose_name="Top position in percent",
            ),
        ),
        migrations.AddField(
            model_name="petinimage",
            name="width_percent_value",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(models.F("width"), "*", models.Value(100)),
                output_field=models.FloatField(),
                verbose_name="Width in percent",
            ),
        ),
    ]
