# Generated by Django 5.2.1 on 2025-06-03 03:08

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
import timezone_field.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "edit_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to edit this object",
                        related_name="%(class)ss_editable",
                        to="auth.group",
                    ),
                ),
                (
                    "view_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to view this object",
                        related_name="%(class)ss_viewable",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tn_ancestors_pks",
                    models.TextField(blank=True, default="", editable=False, verbose_name="Ancestors pks"),
                ),
                (
                    "tn_ancestors_count",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Ancestors count"),
                ),
                (
                    "tn_children_pks",
                    models.TextField(blank=True, default="", editable=False, verbose_name="Children pks"),
                ),
                (
                    "tn_children_count",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Children count"),
                ),
                (
                    "tn_depth",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Depth",
                    ),
                ),
                (
                    "tn_descendants_pks",
                    models.TextField(blank=True, default="", editable=False, verbose_name="Descendants pks"),
                ),
                (
                    "tn_descendants_count",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Descendants count"),
                ),
                ("tn_index", models.PositiveIntegerField(default=0, editable=False, verbose_name="Index")),
                (
                    "tn_level",
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Level",
                    ),
                ),
                (
                    "tn_priority",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                        verbose_name="Priority",
                    ),
                ),
                ("tn_order", models.PositiveIntegerField(default=0, editable=False, verbose_name="Order")),
                (
                    "tn_siblings_pks",
                    models.TextField(blank=True, default="", editable=False, verbose_name="Siblings pks"),
                ),
                (
                    "tn_siblings_count",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Siblings count"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("description", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "edit_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to edit this object",
                        related_name="%(class)ss_editable",
                        to="auth.group",
                    ),
                ),
                (
                    "tn_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tn_children",
                        to="memoria.imagefolder",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "view_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to view this object",
                        related_name="%(class)ss_viewable",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_checksum",
                    models.CharField(
                        db_index=True,
                        help_text="The BLAKE3 checksum of the original file",
                        max_length=64,
                        unique=True,
                        verbose_name="blake3 hex digest",
                    ),
                ),
                (
                    "phash",
                    models.CharField(
                        db_index=True,
                        help_text="The pHash (average) of the original file",
                        max_length=32,
                        verbose_name="perceptual average hash of the image",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        help_text="Size of the original file in bytes",
                        verbose_name="file size in bytes",
                    ),
                ),
                ("original_height", models.PositiveIntegerField(verbose_name="original image height in pixels")),
                ("original_width", models.PositiveIntegerField(verbose_name="original image width in pixels")),
                (
                    "large_version_height",
                    models.PositiveSmallIntegerField(verbose_name="Large size image height in pixels"),
                ),
                (
                    "large_version_width",
                    models.PositiveSmallIntegerField(verbose_name="Large size image width in pixels"),
                ),
                ("thumbnail_height", models.PositiveSmallIntegerField(verbose_name="Thumbnail image height in pixels")),
                ("thumbnail_width", models.PositiveSmallIntegerField(verbose_name="Thumbnail image width in pixels")),
                (
                    "orientation",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Horizontal"),
                            (2, "Mirror Horizontal"),
                            (3, "Rotate 180"),
                            (4, "Mirror Vertical"),
                            (5, "Mirror Horizontal And Rotate 270 Cw"),
                            (6, "Rotate 90 Cw"),
                            (7, "Mirror Horizontal And Rotate 90 Cw"),
                            (8, "Rotate 270 Cw"),
                        ],
                        default=1,
                        help_text="MWG Orientation flag",
                    ),
                ),
                ("title", models.TextField(help_text="Title of the image (used for display only currently)")),
                ("description", models.TextField(blank=True, help_text="MWG Description tag", null=True)),
                ("original", models.CharField(max_length=4096, unique=True, verbose_name="Path to the original image")),
                (
                    "is_dirty",
                    models.BooleanField(
                        default=False,
                        help_text="The metadata is dirty and needs to be synced to the file",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None,
                        help_text="Date the image was deleted or None if it has not been",
                        null=True,
                    ),
                ),
                ("is_starred", models.BooleanField(default=False, help_text="The image has been starred")),
                (
                    "edit_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to edit this object",
                        related_name="%(class)ss_editable",
                        to="auth.group",
                    ),
                ),
                (
                    "view_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to view this object",
                        related_name="%(class)ss_viewable",
                        to="auth.group",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="The folder this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="memoria.imagefolder",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ImageInAlbum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveBigIntegerField(help_text="Order of this image in the album")),
                ("album", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="memoria.album")),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="memoria.image")),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="album",
            name="images",
            field=models.ManyToManyField(related_name="albums", through="memoria.ImageInAlbum", to="memoria.image"),
        ),
        migrations.CreateModel(
            name="ImageSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "edit_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to edit this object",
                        related_name="%(class)ss_editable",
                        to="auth.group",
                    ),
                ),
                (
                    "view_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to view this object",
                        related_name="%(class)ss_viewable",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="image",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="Source of the original image (box, deck, carousel, etc)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="memoria.imagesource",
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "edit_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to edit this object",
                        related_name="%(class)ss_editable",
                        to="auth.group",
                    ),
                ),
                (
                    "view_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to view this object",
                        related_name="%(class)ss_viewable",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonInImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center_x",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "center_y",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Optional description of the region",
                    ),
                ),
                (
                    "exclude_from_training",
                    models.BooleanField(
                        default=False,
                        help_text="For future growth, do not use this box for facial recognition training",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="A Thing is in this Image at the given location",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memoria.image",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person is in this Image at the given location",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_appearances",
                        to="memoria.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="image",
            name="people",
            field=models.ManyToManyField(
                help_text="These people are in the image",
                related_name="images_featured_in",
                through="memoria.PersonInImage",
                to="memoria.person",
            ),
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "pet_type",
                    models.CharField(
                        blank=True,
                        choices=[("cat", "Cat"), ("dog", "Dog"), ("horse", "Horse")],
                        help_text="The type of pet this is",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "edit_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to edit this object",
                        related_name="%(class)ss_editable",
                        to="auth.group",
                    ),
                ),
                (
                    "view_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups allowed to view this object",
                        related_name="%(class)ss_viewable",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PetInImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center_x",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "center_y",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Optional description of the region",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="A Thing is in this Image at the given location",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memoria.image",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        help_text="Pet is in this Image at the given location",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pet_appearances",
                        to="memoria.pet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="image",
            name="pets",
            field=models.ManyToManyField(
                help_text="These pets are in the image",
                related_name="images_featured_in",
                through="memoria.PetInImage",
                to="memoria.pet",
            ),
        ),
        migrations.CreateModel(
            name="RoughDate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="The year (always required)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        help_text="The month (1-12, null if unknown)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        help_text="The day (1-31, null if unknown)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "comparison_date",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            django.db.models.functions.text.Concat(
                                models.F("year"),
                                models.Value("-"),
                                django.db.models.functions.text.LPad(
                                    django.db.models.functions.comparison.Cast(
                                        django.db.models.functions.comparison.Coalesce(
                                            models.F("month"),
                                            models.Value(1),
                                        ),
                                        models.CharField(),
                                    ),
                                    2,
                                    models.Value("0"),
                                ),
                                models.Value("-"),
                                django.db.models.functions.text.LPad(
                                    django.db.models.functions.comparison.Cast(
                                        django.db.models.functions.comparison.Coalesce(
                                            models.F("day"),
                                            models.Value(1),
                                        ),
                                        models.CharField(),
                                    ),
                                    2,
                                    models.Value("0"),
                                ),
                            ),
                            models.DateField(),
                        ),
                        output_field=models.DateField(),
                    ),
                ),
            ],
            options={
                "ordering": ["comparison_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("day__isnull", True), ("month__isnull", False), _connector="OR"),
                        name="day_requires_month",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("year__gte", 1), ("year__lte", 9999)),
                        name="valid_year_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("month__isnull", True),
                            models.Q(("month__gte", 1), ("month__lte", 12)),
                            _connector="OR",
                        ),
                        name="valid_month_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("day__isnull", True),
                            models.Q(("day__gte", 1), ("day__lte", 31)),
                            _connector="OR",
                        ),
                        name="valid_day_range",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("day__isnull", True), ("month__isnull", True)),
                        fields=("year",),
                        name="unique_year_only",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("day__isnull", True), ("month__isnull", False)),
                        fields=("year", "month"),
                        name="unique_year_month",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("day__isnull", False), ("month__isnull", False)),
                        fields=("year", "month", "day"),
                        name="unique_full_date",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="image",
            name="date",
            field=models.ForeignKey(
                blank=True,
                help_text="RoughDate when the image was taken, with as much refinement as possible",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="memoria.roughdate",
            ),
        ),
        migrations.CreateModel(
            name="RoughLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country_code",
                    models.CharField(
                        db_index=True,
                        help_text="Country code in ISO 3166-1 alpha 2 format",
                        max_length=4,
                    ),
                ),
                (
                    "subdivision_code",
                    models.CharField(
                        db_index=True,
                        help_text="State, province or subdivision ISO 3166-2 alpha 2 format",
                        max_length=12,
                        null=True,
                    ),
                ),
                ("city", models.CharField(db_index=True, help_text="City or town", max_length=255, null=True)),
                (
                    "sub_location",
                    models.CharField(
                        db_index=True,
                        help_text="Detailed location within a city or town",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["country_code", "subdivision_code", "city", "sub_location"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("sub_location__isnull", False)),
                        fields=("country_code", "subdivision_code", "city", "sub_location"),
                        name="unique_location_all_fields",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("city__isnull", False), ("sub_location__isnull", True)),
                        fields=("country_code", "subdivision_code", "city"),
                        name="unique_location_no_sub_location",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("city__isnull", True),
                            ("sub_location__isnull", True),
                            ("subdivision_code__isnull", False),
                        ),
                        fields=("country_code", "subdivision_code"),
                        name="unique_location_no_city_sub_location",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("city__isnull", True),
                            ("sub_location__isnull", True),
                            ("subdivision_code__isnull", True),
                        ),
                        fields=("country_code",),
                        name="unique_location_only_country",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="image",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location where the image was taken, with as much refinement as possible",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="memoria.roughlocation",
            ),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "large_image_max_size",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (768, "768px (Tablet/Small Screen)"),
                            (1024, "1024px (Tablet Landscape/Laptop)"),
                            (1920, "1920px (HD/Desktop)"),
                            (2560, "2560px (QHD/Large Desktop)"),
                            (3840, "3840px (4K/HiDPI Desktop)"),
                        ],
                        default=2560,
                        verbose_name="The largest side dimension of generated large images",
                    ),
                ),
                (
                    "large_image_quality",
                    models.PositiveSmallIntegerField(
                        default=90,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="The WebP quality setting for generate large images",
                    ),
                ),
                (
                    "thumbnail_max_size",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (128, "128px (Tiny)"),
                            (256, "256px (Small)"),
                            (512, "512px (Medium)"),
                            (640, "640px (Large)"),
                            (800, "800px (X-Large)"),
                        ],
                        default=512,
                        verbose_name="The largest side dimension of generated image thumbnails",
                    ),
                ),
                (
                    "hash_threads",
                    models.SmallIntegerField(
                        choices=[
                            (-1, "Auto (blake3.AUTO)"),
                            (1, "Single Thread"),
                            (2, "Dual Thread"),
                            (4, "Quad Thread"),
                            (8, "Octa Thread"),
                            (16, "16 Threads"),
                        ],
                        default=4,
                        verbose_name="The number of threads to use when calculating blake3 hashes",
                    ),
                ),
                (
                    "batch_size",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "10"),
                            (20, "20"),
                            (30, "30"),
                            (40, "40"),
                            (50, "50"),
                            (60, "60"),
                            (70, "70"),
                            (80, "80"),
                            (90, "90"),
                            (100, "100"),
                        ],
                        default=10,
                        verbose_name="For indexing and syncing tasks, the default number of images per task",
                    ),
                ),
                (
                    "root_dir",
                    models.CharField(
                        max_length=4096,
                        null=True,
                        unique=True,
                        verbose_name="Root directory where image folders are found",
                    ),
                ),
            ],
            options={
                "verbose_name": "memoria site-wide application settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("large_image_quality__gte", 1), ("large_image_quality__lte", 100)),
                        name="webp_quality_limit_check",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tn_ancestors_pks",
                    models.TextField(blank=True, default="", editable=False, verbose_name="Ancestors pks"),
                ),
                (
                    "tn_ancestors_count",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Ancestors count"),
                ),
                (
                    "tn_children_pks",
                    models.TextField(blank=True, default="", editable=False, verbose_name="Children pks"),
                ),
                (
                    "tn_children_count",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Children count"),
                ),
                (
                    "tn_depth",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Depth",
                    ),
                ),
                (
                    "tn_descendants_pks",
                    models.TextField(blank=True, default="", editable=False, verbose_name="Descendants pks"),
                ),
                (
                    "tn_descendants_count",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Descendants count"),
                ),
                ("tn_index", models.PositiveIntegerField(default=0, editable=False, verbose_name="Index")),
                (
                    "tn_level",
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Level",
                    ),
                ),
                (
                    "tn_priority",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                        verbose_name="Priority",
                    ),
                ),
                ("tn_order", models.PositiveIntegerField(default=0, editable=False, verbose_name="Order")),
                (
                    "tn_siblings_pks",
                    models.TextField(blank=True, default="", editable=False, verbose_name="Siblings pks"),
                ),
                (
                    "tn_siblings_count",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Siblings count"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "tn_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tn_children",
                        to="memoria.tag",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["tn_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagOnImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("applied", models.BooleanField(default=False, help_text="This tag is applied to this image")),
                (
                    "image",
                    models.ForeignKey(
                        help_text="A Tag is on this Image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_tags",
                        to="memoria.image",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="Tag is on this Image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_links",
                        to="memoria.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(
                help_text="These tags apply to the image",
                through="memoria.TagOnImage",
                to="memoria.tag",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "items_per_page",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "10"),
                            (20, "20"),
                            (30, "30"),
                            (40, "40"),
                            (50, "50"),
                            (60, "60"),
                            (70, "70"),
                            (80, "80"),
                            (90, "90"),
                            (100, "100"),
                        ],
                        default=30,
                    ),
                ),
                ("timezone", timezone_field.fields.TimeZoneField(default="America/Los_Angeles", use_pytz=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="imagefolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tn_parent__isnull", True), _negated=True),
                fields=("tn_parent", "name"),
                name="unique_folder_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="imagefolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tn_parent__isnull", True)),
                fields=("name",),
                name="unique_root_folder_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageinalbum",
            constraint=models.UniqueConstraint(fields=("sort_order", "album"), name="sorting-to-album"),
        ),
    ]
