# Generated by Django 5.2.1 on 2025-05-15 19:06

from django.db import migrations


def create_site_settings(apps, schema_editor):  # noqa: ARG001
    SiteSettings = apps.get_model("memoria", "SiteSettings")

    SiteSettings.objects.get_or_create(pk=1)


class Migration(migrations.Migration):
    dependencies = [
        ("memoria", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_site_settings),
    ]
