# Generated by Django 5.2.1 on 2025-06-03 22:27

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("memoria", "0002_create_site_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roughdate",
            name="day",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="The day (1-31, null if unknown)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)],
            ),
        ),
        migrations.AlterField(
            model_name="roughdate",
            name="month",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="The month (1-12, null if unknown)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)],
            ),
        ),
        migrations.AlterField(
            model_name="roughdate",
            name="year",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text="The year (always required)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
    ]
